ViAn/GUI/mainwindow.cpp
ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Fixed the changes that should have been made in the previous request

Basic video

---

ViAn/GUI/mainwindow.cpp
ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h
ViAn/main.cpp

Added stop functionality for video playback

Added stop button functionality

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

+ Added functionality for speeding up or slowing down the playback speed
+ Rearranged the video_player.h file

Video playback speed

---

ViAn/Filehandler/dir.h
ViAn/Filehandler/filehandler.h
ViAn/GUI/mainwindow.cpp
ViAn/ViAn.pro
ViAn/main.cpp

Small fix that enables the program to compile on linux

Fixed linux compatibility

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h
ViAn/main.cpp

Added functionality for juming to next and previous frame (only when paused the video).
Extracted an update function from the run-loop to be able to update the frame shown in the GUI as the user steps through the frames.
Also added the update function to the stop video functionality so it displays the first frame of the video when clicking stop.

Play frame

---

ViAn/GUI/icononbuttonhandler.cpp
ViAn/GUI/icononbuttonhandler.h
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui

Mostly just added the right functionality to the right buttons. Haven't added anything for the filehandling yet

Added fast-forward and backwards buttons and removed the pause button

---

ViAn/GUI/action.h
ViAn/GUI/inputwindow.cpp
ViAn/GUI/inputwindow.h
ViAn/GUI/inputwindow.ui
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/ViAn.pro

You can now create a project using the ui

ADD-Project, creates new project

---

ViAn/GUI/mainwindow.cpp
ViAn/Test/test_video_player.cpp
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

The overlay functionality is extracted to its own class. (No new functionality is added.)

Extract overlay

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/shapes.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added menu bar options for selecting tool and colour for the overlay. (For now the options just affect what is currently drawn on the overlay. And note that the overlay does not update the shapes and colour when the video is paused.)

Add tools overlay

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added functionality to draw on the overlay: Added MainWindow as a listener on the videoFrame and added functionality for mouse pressed/released/moved to update the shape being drawn on the overlay.

Draw overlay

---

ViAn/GUI/mainwindow.cpp

Added returns in eventFilter in MainWindow.

Fixed returns in eventFilter in MainWindow.

---

ViAn/GUI/mainwindow.cpp
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added status bar messages for the overlay tools, and created a function in video_player returning is the overlay-tool is on or off.

added status bar messages for the overlay tools

---

ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/video_player.cpp

Added tests for overlay colour, shape and modified the show_overlay test.

Overlay tests

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Test/test_mainwindow.cpp
ViAn/Test/test_mainwindow.h
ViAn/ViAn.pro
ViAn/main.cpp

Added a test for the statusbar

Statusbar test

---

ViAn/Filehandler/filehandler.cpp
ViAn/Filehandler/filehandler.h
ViAn/Filehandler/project.cpp
ViAn/Filehandler/project.h
ViAn/Filehandler/video.cpp
ViAn/Test/filehandlertest.cpp
ViAn/main.cpp

Load project from file fixed. loads project correctly. Doesnt currently load file ids back into filehandler upon load. So this is to be fixed as a next step.

Load parser

---

ViAn/GUI/mainwindow.cpp
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/shapes.h
ViAn/Video/shapes/arrow.cpp
ViAn/Video/shapes/arrow.h
ViAn/Video/shapes/circle.cpp
ViAn/Video/shapes/circle.h
ViAn/Video/shapes/line.cpp
ViAn/Video/shapes/line.h
ViAn/Video/shapes/rectangle.cpp
ViAn/Video/shapes/rectangle.h
ViAn/Video/shapes/shape.cpp
ViAn/Video/shapes/shape.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added classes for the different shapes of the overlay. Moved the previous shape-header (with enum) to be a superclass for these shapes in a sub-folder to the video_player.

Overlay shapes

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/shapes/arrow.cpp
ViAn/Video/shapes/arrow.h
ViAn/Video/shapes/circle.cpp
ViAn/Video/shapes/circle.h
ViAn/Video/shapes/line.cpp
ViAn/Video/shapes/line.h
ViAn/Video/shapes/pen.cpp
ViAn/Video/shapes/pen.h
ViAn/Video/shapes/rectangle.cpp
ViAn/Video/shapes/rectangle.h
ViAn/Video/shapes/shape.cpp
ViAn/Video/shapes/shape.h

Added pen option in the overlay

Overlay pen

---

ViAn/Filehandler/filehandler.cpp
ViAn/Filehandler/filehandler.h
ViAn/Filehandler/project.cpp
ViAn/Filehandler/project.h

refactored to use ProjectStream for load and save. load_project now also loads file ids.
both save_project and load_project now properly <writes , reads  > <videos,videofile>,<projectinfo, projectfile>

Load save ids

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added undo and clear tool for the overlay.

Overlay undo

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/ViAn.pro
ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/shapes/arrow.cpp
ViAn/Video/shapes/circle.cpp
ViAn/Video/shapes/line.cpp
ViAn/Video/shapes/pen.cpp
ViAn/Video/shapes/rectangle.cpp
ViAn/Video/shapes/shape.h
ViAn/Video/shapes/text.cpp
ViAn/Video/shapes/text.h

Added class to write text on the overlay.
(Also edited some comments.)

Overlay text

---

ViAn/GUI/action.h
ViAn/GUI/inputwindow.cpp
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/GUI/myqaction.cpp
ViAn/GUI/myqaction.h
ViAn/GUI/qtreeitems.cpp
ViAn/GUI/qtreeitems.h
ViAn/ViAn.pro
ViAn/myqaction.cpp
ViAn/myqaction.h

right click menu for project tree view, you can now add videos to project and play them

Make project

---

ViAn/Video/overlay.cpp
ViAn/Video/overlay.h
ViAn/Video/video_player.cpp

Added a map in the overlay containing lists of drawings connected to different frame numbers.
Also changed so that the user can only draw when the video is paused.

Overlay frame

---

ViAn/Filehandler/filehandler.cpp
ViAn/GUI/mainwindow.cpp

Fixed so the load video dialog works on linux.
(Has been tested in both Windows and Linux.)

Fix filedialog

---

ViAn/Video/shapes/arrow.h
ViAn/Video/shapes/circle.h
ViAn/Video/shapes/line.h
ViAn/Video/shapes/pen.h
ViAn/Video/shapes/rectangle.h
ViAn/Video/shapes/text.h

Fix overrides.

---

ViAn/GUI/mainwindow.cpp

Don't press to many times quickly, it will crash

If you click the selected video you play it

---

ViAn/GUI/mainwindow.ui
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

So that i dont have to add them again everytime i make a new branch

Added getter for frame num and added a sliderLayout

---

ViAn/GUI/mainwindow.ui

Added button for switching overlay on and off in toolbar.

added button for switching overlay on and off in toolbar

---

.gitignore
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Test/test_video_player.cpp
ViAn/Test/test_video_player.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

* Changed the pause implementation to use QWaitCondition
* Added signals and slots to handle some video control from the GUI thread

Stop thread

---

ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Added functionality that changes brightness and contrast on the video.
Added getters and setters for the values based on 0-255 input from GUI.

Video contrast

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.ui
ViAn/Video/shapes/analysarea.cpp
ViAn/Video/shapes/analysarea.h
ViAn/Video/video_player.cpp

Added a toolbar for the analysis area tool. The toolbar is toggled on and off, depending on if the analysis area tool is on or off.
Also added clear and undo functionality when using the analysis area tool.

Added toolbar for analysis, and added clear and undo option.

---

ViAn/Filehandler/filehandler.cpp
ViAn/Filehandler/filehandler.h
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/GUI/qtreeitems.cpp
ViAn/GUI/qtreeitems.h
ViAn/Test/filehandlertest.cpp

Merged the two delete functions and cleaned up. When the program asks if you want to remove a video it now only gives the name instead of the whole filepath

Merged the two delete functions into one

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui

Alt+(letter) to select paint tool
SHIFT+C to select color
Ctrl+z to undo
Del to delete selected
+ to zoom in
- to zoom out
maybe some more

changed the way we set shortcuts and addad a lot more

---

ViAn/GUI/mainwindow.cpp
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Fixes crash when switching playback between videos. Also fixes "Finished while threads are still waiting" bug when quitting the program while a video is paused.

Video playback switching

---

ViAn/Video/video_player.cpp

Added so that the cursor is different when in choosing-zoom-area-mode.

Zoom cursor

---

ViAn/Filehandler/bookmark.cpp
ViAn/Filehandler/bookmark.h
ViAn/Filehandler/videoproject.cpp
ViAn/GUI/bookmarkitem.cpp
ViAn/GUI/bookmarkitem.h
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.ui
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Bookmarks are now exported when the project is saved (and not when they're created).
They are exported with the frame number as file name. If there's already a file with that name it will append a number, like `FRAMENR(X).tiff`.

Bookmark save

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui

no functionality yet but it will be easy to connect it in the future

added buttons for jumping between POIs

---

ViAn/Filehandler/filehandler.cpp
ViAn/Filehandler/project.cpp
ViAn/Filehandler/project.h
ViAn/GUI/mainwindow.cpp

saved flag now set on project changed and saved

project saved flag

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Implemented so you now can see the current and total time of the video.

Slider labels

---

ViAn/Filehandler/project.cpp
ViAn/Filehandler/project.h
ViAn/Filehandler/report.cpp
ViAn/Filehandler/report.h
ViAn/Filehandler/videoproject.h
ViAn/GUI/reportgenerator.cpp
ViAn/GUI/reportgenerator.h
ViAn/ViAn.pro
ViAn/main.cpp

exported reports saved in project, saved and loaded to json. Deleting projects now working with reports

Fh export reports

---

ViAn/Filehandler/bookmark.cpp
ViAn/Filehandler/bookmark.h
ViAn/Filehandler/filehandler.cpp
ViAn/Filehandler/project.cpp
ViAn/Filehandler/project.h
ViAn/Filehandler/videoproject.cpp
ViAn/Filehandler/videoproject.h
ViAn/GUI/bookmarkitem.cpp
ViAn/GUI/bookmarkitem.h
ViAn/GUI/bookmarkview.cpp
ViAn/GUI/bookmarkview.h
ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/qtreeitems.cpp
ViAn/GUI/qtreeitems.h

Bookmarks now close when the video closes

Bookmarks close

---

ViAn/GUI/mainwindow.cpp
ViAn/Video/video_player.cpp
ViAn/Video/video_player.h

Fixed a small soft lock that could occur on the slider and cleaned some things up. 
I have found a lot of other small things wrong with the slider that will either come in later pull requests or be ignored because the things aren't that big.
Our slider already have "more" functionality than other sliders, like VLC for example, so it isn't the end of the world if it's not 100% correct.

Fix slider

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h

Since this pull request was closed before I got to do anything about Pär's comment I'm opening a new one. There are no new functionality here just writing the code in a slightly different way.
As it is now there isn't as much repetition in the code and the function set_time_to_label is easier to use in case we need it somewhere else. Still not sure if this is the optimal way to write this. The function set_slider_labels maybe isn't needed, but I didn't wan't to have that much code in update_video.

More slider labels

---

ViAn/GUI/reportgenerator.cpp
ViAn/GUI/reportgenerator.h
ViAn/Test/test_report_generator.cpp

Now the frame and time is added to the word document followed by a description. There is also a frame, time and description "header" so let say the person write something like "this is the suspect" then it will show
Description: this is the suspect
in the word document.

Export reports

---

ViAn/GUI/mainwindow.cpp
ViAn/GUI/mainwindow.h
ViAn/GUI/mainwindow.ui
ViAn/Test/test_report_generator.cpp

Added an area showing the current frame number and the option to jump do a desired frame.

Frame number
