GeorgeYildiz/TDDD96-group6

- ViAn/Video/overlay.cpp
Fixed a bug in overlay when drawing a line, it had the wrong end points.
> Draw line bugfix

- ViAn/Video/overlay.cpp
- ViAn/Video/video_player.cpp
Added so that overlay is not trying to draw anything if no video is loaded.
> Overlay check loadedvideo

- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Extracted current frame calculations to separate function. Also changed the `set_playback_frame` so that next/prev frame now works in connection with pausing a clip.
> Fixed next/prev frame

- ViAn/GUI/mainwindow.cpp
- ViAn/Test/test_video_player.cpp
- ViAn/Test/test_video_player.h
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Functions `set_playback_frame` and `stop_video` is removed and variable `current_frame` is removed. The old stop functionality is added to the new `on_stop_video` function.
> Removed unused code in video player

- ViAn/Test/test_video_player.cpp
- ViAn/Test/test_video_player.h
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Added tests for contrast and brightness, and changed the representation on these values in the videoplayer. Now the 0-255 values are stored in the video player and recalculated to alpha and beta values in the contrast-function, instead of being calculated in the getters and setters.
> Added tests for contrast/brightness

- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Fixed the drawing on the overlay to work with the new way of scaling the frame. To do this `scale_position()` is updated to handle the empty parts of the QLabel that is left when the QLabel don't have the same ratio as the video. Also needed to add new variables to remember the QLabel size in the videoplayer.
> Fixed overlay with new scaling functionality

- ViAn/Video/shapes/zoomrectangle.cpp
- ViAn/Video/shapes/zoomrectangle.h
- ViAn/Video/video_player.cpp
Now the zoom area follows the ratio of the video. The calculation is done when the mouse is moved and the position is updated in ZoomRectangle.
Also added so that the zoom area is reset when the user starts a zoom procedure.
> Added so that the zoom area follows the ratio of the video.

- ViAn/Test/test_video_player.cpp
- ViAn/Test/test_video_player.h
- ViAn/Video/video_player.cpp
Added test for the new `set_current_frame` function. Fixed the next/previous frame tests. (Also changed video overlay test, because it requires the video to be stopped.)
> Added tests for video next/previous frame

- ViAn/GUI/mainwindow.cpp
- ViAn/GUI/mainwindow.h
- ViAn/GUI/mainwindow.ui
- ViAn/ViAn.pro
- ViAn/Video/overlay.h
- ViAn/Video/shapes/analysarea.cpp
- ViAn/Video/shapes/analysarea.h
- ViAn/Video/shapes/shape.h
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Added a simple tool for choosing an area. It's not connected to anything yet, only shown on the frame. It uses a new class which draws a polygon between a list of points that the user selects by clicking on the video while in the analysis-area-tool-mode (chosen through en option in View-menu). You can not remove any points you've chosen or start over with the area, you can only hide or show it (which is the same as being able to edit it or not being able to edit it).
> Added simple analysis area tool

- ViAn/Video/overlay.cpp
- ViAn/Video/overlay.h
- ViAn/Video/shapes/text.cpp
- ViAn/Video/shapes/text.h
Added so that the user gets to choose font scale when entering a text (the font scale is used by opencv to multiply with the default font size, which is depending on what font is used). To do this, the CustomDialog class (found in Library) has been used.
> Selectable text font scale option

- ViAn/Video/video_player.cpp
Fixed error when converting mouse coordinates to frame coordinates. I was not aware that the frame was not centered horisontally in the QLabel (it is centered vertically), so that's now fixed. Also found that parentheses was missing in the vertical calculation, so that the additional area above the video was also scaled in the calculations, which it shouldn't.
> Fixed error with the drawing tool when scaling the window.

- ViAn/Video/shapes/zoomrectangle.cpp
- ViAn/Video/shapes/zoomrectangle.h
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Added delete of the zoom_area in the video_player, and added a destructor in ZoomRectangle, because Qt was showing a warning about this. Also moved the initialization of the overlay to the headerfile to make the code more uniform.
> Added zoom_area destructor

- ViAn/GUI/bookmarkview.cpp
- ViAn/GUI/bookmarkview.h
- ViAn/GUI/mainwindow.cpp
- ViAn/GUI/mainwindow.h
- ViAn/ViAn.pro
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
A simple bookmark tool is implemented. The *-button now adds the current frame to the bookmark list to the right. It is represented with a thumbnail as well as a text description (entered by the user). The images used are exported by the video player and stored as tiff images in a bookmarks-folder in the project-folder.
Note that the bookmarks now have no effect. Nothing happens when selecting a bookmark in the list.
> Simple bookmark tool

- ViAn/Video/video_player.h
Removed method in header that is not in cpp-file anymore (replaced by slots/signals).
> Removed method in header.

- ViAn/GUI/bookmark.cpp
- ViAn/GUI/bookmark.h
- ViAn/GUI/bookmarkview.cpp
- ViAn/GUI/bookmarkview.h
- ViAn/GUI/mainwindow.cpp
- ViAn/GUI/mainwindow.h
- ViAn/ViAn.pro
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
*Pull request #100!*
A class ```Bookmark``` has been created (inheriting ```QListWidgetItem```) that holds the bookmark information. These ```Bookmark```s are added to the document list view. Clicking them invokes a method that jumps to the frame associated with the bookmark, though it **only works when the video is paused**, since the updated jump-to-frame functionality is still in the non-merged slider-branch.
Also fixed the export of frames, so that they are not scaled but stored as original size. (In the process I also cleaned up the code for scaling frames.)
> Added bookmark class, simple jump to frame, and no-scale export images

- ViAn/GUI/bookmark.cpp
- ViAn/GUI/bookmark.h
- ViAn/GUI/bookmarkitem.cpp
- ViAn/GUI/bookmarkitem.h
- ViAn/GUI/bookmarkview.cpp
- ViAn/GUI/bookmarkview.h
- ViAn/GUI/mainwindow.cpp
- ViAn/ViAn.pro
Changed the bookmark representation to make it easier to store bookmarks. There's a class `BookmarkItem` and objects of this class is added to the QListWidget holding the bookmarks. Within the `BookmarkItem` is a pointer to a `Bookmark`-object holding the information that can be stored.
> Separated Bookmark and BookmarkItem

- ViAn/GUI/mainwindow.cpp
- ViAn/GUI/mainwindow.h
- ViAn/GUI/mainwindow.ui
- ViAn/Test/test_video_player.cpp
- ViAn/Test/test_video_player.h
- ViAn/Video/shapes/analysarea.cpp
- ViAn/Video/shapes/analysarea.h
- ViAn/Video/shapes/shape.h
- ViAn/Video/shapes/zoomrectangle.cpp
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Added the option to choose an area to include or wxclude in the analysis. Changed the representation so that the area to exclude from analysis is marked grey, and the area to include is unmarked.
Also added tests, extracted opacity to a constant, and fixed a possibly uninitialised warning.
> Added option to invert the analysis area.

- ViAn/GUI/bookmarkitem.cpp
- ViAn/GUI/mainwindow.cpp
- ViAn/GUI/mainwindow.h
- ViAn/GUI/mainwindow.ui
- ViAn/Test/test_video_player.cpp
- ViAn/ViAn.pro
- ViAn/Video/analysisoverlay.cpp
- ViAn/Video/analysisoverlay.h
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
An overlay for the analysis is now created. It can be turned on and off from the menu and toolbar.
Since there're no analysis yet, it only shows some squares during the first 1 frames for now.
Areas can be added to the overlay by using `add_area` with a frame number and coordinates for two corners of the area.
> Analysis overlay

- ViAn/GUI/fpsdialog.cpp
- ViAn/GUI/fpsdialog.h
- ViAn/ViAn.pro
To get the FPS, create an instance of the `FPSDialog` class and call `get_fps()` with the parent window.
There're some constants in the FPS dialog class that can be adjusted at will (I just picked something looking reasonable).
> Added FPS dialog class

- ViAn/Test/test_video_player.cpp
- ViAn/Video/overlay.cpp
- ViAn/Video/overlay.h
- ViAn/Video/shapes/arrow.cpp
- ViAn/Video/shapes/arrow.h
- ViAn/Video/shapes/circle.cpp
- ViAn/Video/shapes/circle.h
- ViAn/Video/shapes/line.cpp
- ViAn/Video/shapes/line.h
- ViAn/Video/shapes/pen.cpp
- ViAn/Video/shapes/pen.h
- ViAn/Video/shapes/rectangle.cpp
- ViAn/Video/shapes/rectangle.h
- ViAn/Video/shapes/shape.cpp
- ViAn/Video/shapes/shape.h
- ViAn/Video/shapes/text.cpp
- ViAn/Video/shapes/text.h
Read and write methods for the overlay (and all shapes) have been implemented. They're not used and **NOT** connected to the filehandler yet.
To do this `read()` and `write()` methods have been added to the overlay and all shapes (class `shape` have general `read_shape()` and `write_shape()` with the common parameters for all shapes). Empty constructors has also been added, and each shape now knows what type it is.
**The overlay does NOT know what video it's connected too.**
(Also fixed some misspelled comments and refactored a method-name.)
> Read&Write overlay

- ViAn/Video/analysisoverlay.cpp
- ViAn/Video/analysisoverlay.h
Changed so that `AnalysisOverlay` takes a `cv::Rect` as inupt.
Also added constants for the graphical representation of the areas.
> Changed representation in AnalysisOverlay

- ViAn/Filehandler/project.cpp
An old variable name from the `export_report` pull request. (Patrik changed this variable name in his pull request.)
> Fixed old variable name.

- ViAn/Filehandler/bookmark.cpp
- ViAn/Filehandler/bookmark.h
- ViAn/GUI/mainwindow.cpp
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
Bookmarks are now exported as `VIDEOFILENAME_FRAME(X).tiff`.
(For example `seq_01.mp4_337(2).tiff`.)
> Added video name to bookmark file name.

- ViAn/GUI/mainwindow.cpp
Only this funcionality is added. We might want the buttons to be disabled when we are at the first frame and the same on the last frame. Because now it says it went back a frame even when it's already on the first frame.
Might add it later or if you complain enough.
> Added the ability to see the frame number in the statusbar after clicking either the next frame or preivious frame button

- ViAn/Filehandler/bookmark.cpp
- ViAn/Filehandler/bookmark.h
- ViAn/GUI/mainwindow.cpp
- ViAn/Test/overlayintegrationtest.cpp
- ViAn/Video/video_player.cpp
- ViAn/Video/video_player.h
A timestamp in **milliseconds** has now been added to the `bookmark`.
The retrieving of frame, framenumber and time when clicking the bookmark-button has also been moved so that the bookmark stores the frame at the moment the user clicks the button (previously it was stored at the moment the user had entered the text description and clicked OK).
> Bookmark time

- ViAn/Filehandler/filehandler.cpp
- ViAn/Test/test_report_generator.cpp
- ViAn/main.cpp
Testing by default leads to multiple test word reports in recent history
> Turned off testing by default. fixed a test.
